language: node_js

node_js:
  - 6

sudo: false

env:
  global:
    # encrypted Sauce Labs sub-account user name
    - secure: ghtK6PdDy13ruL+HGT4doVcUkl8pyzukY1gkHbkIAL8BrOc0eQdGBnAxKpPGZJv/8upWyul69DgXKg26cbS633Gfp0NjM/YPUh6wEgTg46Zjirw1ejX7xmqsQUGukZXOXNsll7/Syql+KEn8ao+JOAh+gjkFfNY2mxD6Oxs56Sc=
    # encrypted Sauce Labs sub-account token
    - secure: LJw6Cd29/2EdavwQyALzgteQM5+tasvJu0FpS9HJnJPw77HAEl+u8HhRzV2V+/4n2ZMOG9lvDjS1ON+crAolXvo8FO607QNxKFfaMRU2ESynr7+A+itLD/4x3ljPXh72Mypw4Sh0geeVYyZ613jfjzXwKK6lazE/ZhzfcyD4hYk=

before_script:
  - npm install -g gulp

# script:
#   - gulp tests
#   - gulp tests:integration
